### PR TITLE
armor to armour

### PR DESCRIPTION
**Pull request by OH296**
changed all instances of armor to armour including armory to armoury

### CODE REVIEW

**Comment by GalacticChimp** [comment]
missed a few:

image

**Review by GalacticChimp — CHANGES_REQUESTED** [review]
Please look at my comments. The main issue seems to be that proper names got decapitalized, for example Power **A**rmor => Power **a**rmour

**Comment by OH296** [comment]
@GalacticChimp  really sorry completely. redone this i was on my way out and put the pr in when i really should't have have re-done to account for case sensitivity and lexicanium correctness

**Comment by GalacticChimp** [comment]
> @GalacticChimp really sorry completely. redone this i was on my way out and put the pr in when i really should't have have re-done to account for case sensitivity and lexicanium correctness

np, don't worry, it's just some capitalization issues in a game, not biomedical software

**Comment by GalacticChimp** [comment]
ayyy, sorry for the conflicts, I merged another PR with some changes. I'll prepare another PR to fix the conflicts.

**Comment by GalacticChimp** [comment]
Fixed all merge conflicts: https://github.com/OH296/ChapterMaster/pull/1
Please CR, after that we can merg my PR into your repo, then merge this PR
Sorry for the trouble, forgot I was not supposed to merge any armo(u)r changes

**Comment by OH296** [comment]
@GalacticChimp Not to worry should all be good now.

**Comment by OH296** [comment]
@GalacticChimp solved that final ui error should make it good to go

**Review by GalacticChimp — APPROVED** [review]

**Pull request merged**
