### PR TITLE
updated README

### PR DESCRIPTION
**Pull request by GalacticChimp**
Our readme looked a bit poor, so I decided to add come content there

### CODE REVIEW

**Comment by ZAB909** [comment]
Looks good, I'd say tell people to download git kraken and link a tutorial for it

**Comment by GalacticChimp** [comment]
> Looks good, I'd say tell people to download git kraken and link a tutorial for it

sure, I'll add it today

**Comment by GalacticChimp** [comment]
@ZAB909, updated

**Comment by OH296** [comment]
I know we have the discord but that pretty quickly get's populated by lots of community members of all sorts do. Do we link to a different resource that can be kept by just contributors to list off what we're all currently working on and have more or less mutually agreed on as a work list?  Just be useful so when i'm editing files i defiantly know i'm not stepping on anyones feet so to speak.
Otherwise looks good!

**Comment by GalacticChimp** [comment]
> I know we have the discord but that pretty quickly get's populated by lots of community members of all sorts do. Do we link to a different resource that can be kept by just contributors to list off what we're all currently working on and have more or less mutually agreed on as a work list? Just be useful so when i'm editing files i defiantly know i'm not stepping on anyones feet so to speak. Otherwise looks good!

Sorry, I don't follow?

**Review by ZAB909 — APPROVED** [review]
good and str8 to the point

**Pull request merged**
