### PR TITLE
Hotfix: deleted logs which caused slow downs

### PR DESCRIPTION
**Pull request by felipeStouvenel**
# Hotfix
- Deleted a coment which was causing slow downs on system generation

### CODE REVIEW

**Review by OH296 — APPROVED** [review]
All looks good.

**Review by GalacticChimp — CHANGES_REQUESTED** [review]
doesn't compile

image

**Comment by OH296** [comment]
> doesn't compile
> 
> image

these are solved by the  #128

**Comment by GalacticChimp** [comment]
> > doesn't compile
> > image
> 
> these are solved by the #128 and were caused by #117 i think

ok, but `ZAB909:main` still needs to be merged/rebased onto this branch

**Comment by OH296** [comment]
> > > doesn't compile
> > > image
> > 
> > 
> > these are solved by the #128 and were caused by #117 i think
> 
> ok, but `ZAB909:main` still needs to be merged/rebased onto this branch
rebased locally and runs fine

**Review by GalacticChimp — APPROVED** [review]

**Pull request merged**
